### ISSUE TITLE
Query 不能切换到testnet

### ISSUE THREAD

**Issue by necokeine** [cssmagic/Nasa.js#11]
Query没有走向testnet

**Comment by cssmagic** [comment]
由于 `query()` 请求并不是通过钱包扩展发出的，需要开发者通过 `Nasa.env.set()` 手动设置当前环境。

这确实有些割裂——有时由钱包扩展决定，有时由 Nasa 自己决定。因此我向星云团队申请增加 ”获取钱包扩展当前环境设置“ 的接口，参见：
https://github.com/nebulasio/WebExtensionWallet/issues/38
